### ISSUE TITLE
I have a problem compiling ethereum-bignumber for wasm32-unknown-unknown

### ISSUE THREAD

**Issue by k06a** [rust-blockchain/ethereum#1]
Any ideas how to solve it? I currently switched to different library, but wish to let you know about this problem.

![image](https://user-images.githubusercontent.com/702124/65259019-a375af00-db0c-11e9-9475-7e106f03bf0c.png)

**Comment by sorpaas** [comment]
This should have been fixed. We're using `ethereum` in Frontier `no_std` with no problem.
