### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by gakonst** [rust-blockchain/ethereum#39]
It'd be nice if you can release 0.12.0, so we can update `primitive-types` and `ethereum` in Sputnik: https://github.com/rust-blockchain/evm/pull/101

**Comment by gakonst** [comment]
Bump, please! This is important, people cannot build repositories that depend on newer versions of ethereum-types and sputnik EVM until this is done and updated on sputnik!

**Comment by sorpaas** [comment]
This is done. Sorry for the delay!
